name: CalendarImporter
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget: "15.0"
targets:
  CalendarImporter:
    type: application
    platform: iOS
    sources:
      - CalendarImporter
    settings:
      base:
        INFOPLIST_FILE: CalendarImporter/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.calendarimporter
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
    info:
      path: CalendarImporter/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
